name: Swift Doc
  # You may pin to the exact commit or the version.
  # uses: SwiftDocOrg/swift-doc@f441648bcb8a6b07a3724bc1af2488e8a6e6c184
  uses: SwiftDocOrg/swift-doc@1.0.0-beta.5
  with:
    # A path to a directory containing Swift (`.swift`) files in your workspace
    # default is ./Sources
    inputs: ./TestAppSite
    # The name of the module
    module-name: TestAppSite
    # The output format (commonmark or html)
    # optional, default is commonmark
    format: html 
    # The base URL for all relative URLs generated in documents
    base-url: # optional, default is ./
    # The path for generated output
    output: # default is ./.build/documentation
